name: Robot Framework Tests
 
on: push
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: clonando para o repositorio na maquina virtual
        # run: echo clonando para o repositorio na maquina virtual
        uses: actions/checkout@v4
 
      - name: Instalação da versão 3.12 do Python
        # run: echo Instalação da versão 3.12 do Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
 
      - name: Instalação das depedências do Projeto
        # run: echo Instalação das depedências do Projeto
        run: |
          pip install robotframework
          pip install robotframework-requests
 
      - name: Executando os testes de API do Robot
        # run: echo Executando os testes de API do Robot
        run: |
          robot --outputdir results/ tests/

      - name: Salvando o Report dos Testes
        # run: echo Salvando o Report dos Testes
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-report
          path: results/
